name: Weather Pipeline CI/CD

on:
  push: # Triggers the workflow on push events to the repository
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

permissions:
  contents: write

jobs:
  test_and_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Checks out the repository code and version of GitHub Actions

      - name: Use node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm # Caches the npm modules to speed up subsequent workflow runs
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }} # Creates a unique cache key based on the OS and package-lock.json file hash

      - name: Install dependencies
        run: npm ci # Installs the project dependencies using npm

      - name: Fetch latest Weather
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # Uses the WEATHER_API_KEY secret from the repository settings.
          CITY: ${{ secrets.CITY}} # Uses the CITY secret from the repository settings.
        run: node fetchWeather.js # Runs the fetchWeather.js script to fetch the latest weather data

      - name: Commit weather data if changed # Commits and pushes changes to weather.json if there are any changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/weather.json data/weather_log.csv || true 
          git commit -m "ci: update weather data" || echo "No changes to commit" 
          git push || echo "Push failed or no changes"

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }} # Triggers a deploy on Render using the RENDER_DEPLOY_HOOK secret from the repository settings.